export enum UnitraErrorCode {
  ASSERT_ERROR = 'ASSERT_ERROR',
  HOOK_RUN_ERROR = 'HOOK_RUN_ERROR',
  PLUGIN_RESOLUTION_ERROR = 'PLUGIN_RESOLUTION_ERROR',
  RESOLVE_ERROR = 'RESOLVE_ERROR',
  SEMVER_ERROR = 'SEMVER_ERROR'
}
