export enum UnitraErrorCode {
  ASSERT_DEF_ERROR = 'ASSERT_DEF_ERROR',
  ASSERT_REF_ERROR = 'ASSERT_REF_ERROR',
  HOOK_RUNNER_ERROR = 'HOOK_RUNNER_ERROR',
  PLUGIN_RESOLUTION_ERROR = 'PLUGIN_RESOLUTION_ERROR'
}
