name: Build

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build.yml
      - packages/**
      - package.json
      - pnpm-lock.yaml

  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Type Check
        run: pnpm lint

      - name: Test
        run: pnpm test:linux
